### ISSUE TITLE
structure ignores mimetype of uploaded file to determine content type

### ISSUE THREAD

**Issue by djay** [plone/mockup#393] opened 2014-07-15 08:44 UTC
This line ignores the mimetype and instead only uses filename to determine content type to use. 

https://github.com/collective/wildcard.foldercontents/blob/master/wildcard/foldercontents/views.py#L861

Instead it should be doing something more similar to https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/filerepresentation.py#L408

**Comment by vangheem** [comment] 2015-07-21 15:42
Duplicate of https://github.com/plone/mockup/issues/394

**Closed by vangheem** 2015-07-21 15:42 UTC
Labels: bundle:foldercontents, pattern:structure
