### ISSUE TITLE
the warning message shown when filtering contents doesn't go away when removing all the filters

### ISSUE THREAD

**Issue by arsenico13** [plone/mockup#812] opened 2017-10-04 16:39 UTC
If you are in Contents view and try to apply a filter, a warning message appears, saying:
_"Can not order items while querying"_

Aside the fact that this message is misleading
(as I explained here https://github.com/collective/plone.app.locales/issues/173), 
**that message never goes away, even if you remove all the filters**.
You have to reload the entire page to make it disappear.

**Comment by thet** [comment] 2020-02-03 18:14
Duplicate of: https://github.com/plone/mockup/issues/672

**Closed by thet** 2020-02-03 18:14 UTC
Labels: 01 type: bug, 04 type: enhancement
