### ISSUE TITLE
Too few items translated

### ISSUE THREAD

**Issue by pbauer** [plone/mockup#536] opened 2015-07-20 15:55 UTC
I translated most strings into german in https://github.com/collective/plone.app.locales/commit/cc254757  (might need another pair of eyes). 
But a lot of the UI (especially in folder_contents) is still in english and possibly need the _t() around them. 

Steps to reproduce: 
- use master of mockup and of plone.app.locales
- switch your site to german
- optional: clear you localstorage if you change something in widgets.po

**Comment by vangheem** [comment] 2015-07-20 15:58
Everything should be translatable. All the icon names and popover content is translated in python/page templates now.

See https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/copy.py#L24

and 

https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/templates/delete.pt

**Comment by davilima6** [comment] 2015-07-20 19:16
I confirm the same issue in `pt-br`, only difference I still didn't merge p.a.locales widget branch into master so it needs to be checked out before firing up the instance.

**Comment by vangheem** [comment] 2015-07-20 19:19
Everything is translatable--just need people to write the translations.

**Comment by vangheem** [comment] 2015-07-21 15:41
Closing as duplicate of https://github.com/plone/mockup/issues/488 ?

re-open if I'm wrong.

**Comment by pbauer** [comment] 2015-07-21 18:05
Not really a puplicate, this only deals with the fact that some items are missing the ``_t('')``-method.

One example: 
``mockup/patterns/structure/js/views/app.js`` in line 329 "title: 'Rearrange'," and "tooltip: 'Rearrange folder contents'" is not translatable. 

Actually not one button in the bar is translatable, but most popups in the menu are translatable. E.g. the popup for columns is translated but the title of the form is not (``mockup/patterns/structure/js/views/columns.js`` line 12).

Sorry for being a pest. I will help working on that as well.

**Comment by vangheem** [comment] 2015-07-21 18:24
As I've said, mostly everything is translated in plone.app.content: https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/__init__.py

I've updated those 2 buttons that were not translatable: https://github.com/plone/mockup/commit/e92665af2f8bcd8c53ee3d91d60565e29ade61fe

**Closed by vangheem** 2015-07-21 18:24 UTC

**Comment by vangheem** [comment] 2015-07-21 18:25
Do not look at `mockup/patterns/structure/js/pattern.js` for translations. That's not where they are defined.

**Comment by pbauer** [comment] 2015-07-21 18:49
Sorry, I totally ignored the comment where you pointed at plone.app.content. Thanks. 
I fixed the missing _t in columns.

**Comment by vangheem** [comment] 2015-07-21 19:01
Thanks!
